# vim: ft=yaml.docker-compose

services:
  anthias-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=development
    restart: always
    volumes:
      - anthias-data:/data
      - ./:/usr/src/app/

  anthias-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    depends_on:
      - anthias-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    restart: always
    volumes:
      - anthias-data:/data

  anthias-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - anthias-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always
    volumes:
      - anthias-data:/data

  redis:
    image: redis:alpine
    platform: linux/arm64
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  anthias-nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 8000:80
    environment:
      - HOME=/data
    depends_on:
      - anthias-server
      - anthias-websocket
    restart: always
    volumes:
      - anthias-data:/data:ro
      - ./static:/data/screenly/staticfiles:ro

  anthias-viewer:
    image: screenly/anthias-viewer:16ca60e-pi4-64
    mem_limit: 2048000k 
    depends_on: 
      - anthias-server
    environment:
      - HOME=/data
      - PORT=80
      - NOREFRESH=1
      - LISTEN=anthias-nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    restart: always
    shm_size: 512000kb 
    volumes:
      - resin-data:/data
      - /home/pios/.asoundrc:/data/.asoundrc
      - /home/pios/.screenly:/data/.screenly
      - /home/pios/screenly_assets:/data/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./:/usr/src/app/

volumes:
    anthias-data:
    redis-data:
    resin-data: